### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by michela12345** [yingstat/intePareto#1]
Hey, I tried to install your package on R but it does not find it on CRAN in any version for me. How do I get it installed?

**Comment by yingstat** [comment]
Hi, intePareto is now maintained in github.
You can install directly like this:
library(devtools)
install_github("yingstat/intePareto")

**Comment by michela12345** [comment]
Thank you, I have another question:






*res.1 <- doMatch(rnaMeta = rna_seq, # metadata of RNA-SeqchipMeta =
chip_noH3K36me3, # metadata or ChIP-Seqregion = "gene body", # specify the
region#method = "highest", # specify the strategy to do the
matchensemblDataset = "celegans_gene_ensembl" # specify the dataset of
corresponing species)*

this one is the function that you use but I do not understand what I have
to insert in "*region*" because if I use " *region = "gene body"* ", I have
this error: *region must be specified. *

The *method* parameter, I did not enter it as you wrote on the site. I
insert the photo of my screen so you can unserdand better what I'm doing.
[image: image.png]

Thank you,
Best regards,
Michela

Il giorno gio 16 feb 2023 alle ore 17:25 Ying ***@***.***> ha
scritto:

**Comment by yingstat** [comment]
Hi, try use "genebody" or "promoter" instead of "gene body" to set the region parameter.

**Comment by michela12345** [comment]
I try with genebody and promoter, but it still doesn't work

Il giorno lun 20 feb 2023 alle ore 16:37 Ying ***@***.***> ha
scritto:

**Comment by yingstat** [comment]
Can you show me your scripts and the error and the example data set?
I have no clue about how it doesn't work.

**Comment by michela12345** [comment]
I this is my script and the error



*library(intePareto)*


















*library(Rsamtools)library(biomaRt)rna_seq <-
read.table(file="RNA-seq.txt",header = TRUE)rep2_SG2_inteK36 <-
scanBam("rep2_SG2_inteK36_tagged_dedup.bam")rep2_SG2_non_inteK36 <-
scanBam("rep2_SG2_non_inteK36_tagged_dedup.bam")rep2_SG2_inteK4 <-
scanBam("rep2_SG2_inteK4_tagged_dedup.bam")rep2_SG2_non_inteK4 <-
scanBam("rep2_SG2_non_inteK4_tagged_dedup.bam")ensembl <-
useEnsembl(biomart="ensembl", dataset="celegans_gene_ensembl")res.1 <-
doMatch(rnaMeta = rna_seq, # metadata of RNA-Seq                 chipMeta =
rep2_SG2_inteK36, # metadata or ChIP-Seq                 region =
"genebody", # specify the region                 #method = "highest", #
specify the strategy to do the match                 ensemblDataset =
ensembl                 # specify the dataset of corresponing species)*


*Errore in checkInputParam(rnaMeta = rnaMeta, chipMeta = chipMeta, region =
region,  :   arguments rnaMeta, chipMeta, region,           method, host,
ensemblDataset must be specified*

this is my rna-seq file but I don't kwno how to show you my bam file

[image: image.png]




Il giorno lun 20 feb 2023 alle ore 17:22 Ying ***@***.***> ha
scritto:

**Comment by yingstat** [comment]
The error tells you that the "ensemblDataset must be specified". 
Can you make sure the ensembl object is correct?
I can not see your attached image.

**Comment by yingstat** [comment]
Since the download problem is solved, so I closed this issue now.

**Comment by michela12345** [comment]
But I think my ensemble is correct, I see that you, in the example use
: "mmusculus_gene_ensembl" but I insert:
*ensembl <- useEnsembl(biomart="ensembl", dataset="celegans_gene_ensembl")*
and the "celegans_gene_ensembl" is correct, and, like you can see from my
photo, the file is not empty


Il giorno lun 20 feb 2023 alle ore 18:24 Ying ***@***.***> ha
scritto:

**Comment by yingstat** [comment]
Try ensemblDataset = "celegans_gene_ensembl"
To see the different datasets available within a biomaRt you can e.g. do: mart = useMart('ensembl'), followed by listDatasets(mart).

**Comment by michela12345** [comment]
I try what you told me but I still have the problem, but the name of the
dataset is correct.Sorry to bother you but I just can't figure out what I'm
doing wrong

Il giorno lun 20 feb 2023 alle ore 18:59 Ying ***@***.***> ha
scritto:
